baseURL = 'https://skills.dbj.org/'
languageCode = 'en-us'
title = 'DBJ METHOD Skills'
theme = 'PaperMod'
paginate = 10

[params]
  author = 'Dusan B. Jovanovic'
  description = 'Direct mapping to AI Readiness'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  comments = true
  TocOpen = false
  defaultTheme = 'auto'
  homeInfoParams = { Title = 'DBJ METHOD Skills', Content = 'Direct mapping to AI Readiness' }
  homeBanner = '/images/banner.png'

[params.profileMode]
  enabled = false

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 2
  [[menu.main]]
    name = 'DBJ Method'
    url = 'https://method.dbj.org'
    weight = 3
